name: Deploy dotcom website

on:
  push:
    branches:
      - main

env:
  DEPLOY_DEST_PATH: /srv/production-deploy/${{ github.repository }}
  SERVICE_NAME: carina-dotcom-website
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Upload production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: built-artifacts
          path: |
            .next
            public
            node_modules
            package.json
            package-lock.json

  deploy:
    runs-on: self-hosted
    needs: build

    steps:
      - name: Download production artifacts
        uses: actions/download-artifact@v2
        with:
          name: built-artifacts
          path: ${{ runner.temp }}/built-artifacts

      - name: Clean destination directory
        run: rm -rf ${{ env.DEPLOY_DEST_PATH }}/*

      - name: Move artifacts to destination
        run: |
          mkdir -p ${{ env.DEPLOY_DEST_PATH }}
          mv ${{ runner.temp }}/built-artifacts/* ${{ env.DEPLOY_DEST_PATH }}/

      - name: Restart service
        run: sudo systemctl restart ${{ env.SERVICE_NAME }}